FROM nginx:alpine

RUN apk add --no-cache openssl

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 3650 \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/server.key \
    -out /etc/nginx/ssl/server.crt \
    -subj "/C=MA/ST=Rabat/L=Rabat/O=UM6P/OU=IT/CN=netupgrade.um6p.ma"

EXPOSE 80 8444